import{S as a,i as c}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const f="45301554-42ab9bd7e2b914874aa400849";function u(n){const o="https://pixabay.com/api/?key="+f+"&q="+encodeURIComponent(n)+"&image_type=photo&orientation=horizontal&safesearch=true";return fetch(o).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>e.hits).catch(e=>(console.error(e),[]))}function m(n){const o=document.querySelector(".gallery");o.innerHTML=n.map(e=>`<a class="gallery__item" href="${e.largeImageURL}">
        <img class="gallery__image" src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}" width="360" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${e.likes}</p>
          <p class="info-item"><b>Views:</b> ${e.views}</p>
          <p class="info-item"><b>Comments:</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>`).join("")}const i=document.querySelector(".search-form"),d=document.querySelector(".gallery");let p=new a(".gallery a");i.addEventListener("submit",n=>{n.preventDefault();const o=i.querySelector(".search-input").value.trim();o!==""&&(d.innerHTML="",u(o).then(e=>{e.length===0?y():(m(e),p.refresh())}).catch(e=>{console.error(e)}).finally(()=>{i.reset()}))});function y(){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",messageColor:"#fff",color:"#ef4040",icon:null})}
//# sourceMappingURL=commonHelpers.js.map
